/-- Turn a unicode character into a LaTeX representation.

Some of this is drawn from https://github.com/leanprover-community/lean/blob/master/extras/latex/lstlean.tex -/
def Char.toLatex : Char → String
  | 'α' => "\\alpha"
  | 'β' => "\\beta"
  | 'γ' => "\\gamma"
  | 'δ' => "\\delta"
  | 'ε' => "\\varepsilon"
  | 'ζ' => "\\zeta"
  | 'η' => "\\eta"
  | 'θ' => "\\theta"
  | 'ι' => "\\iota"
  | 'κ' => "\\kappa"
  | 'λ' => "\\lambda"
  | 'μ' => "\\mu"
  | 'ν' => "\\nu"
  | 'ξ' => "\\xi"
  | 'π' => "\\pi"
  | 'ρ' => "\\rho"
  | 'σ' => "\\sigma"
  | 'τ' => "\\tau"
  | 'φ' => "\\varphi"
  | 'χ' => "\\chi"
  | 'ψ' => "\\psi"
  | 'ω' => "\\omega"
  | 'ϖ' => "\\varpi"
  | 'Γ' => "\\Gamma"
  | 'Δ' => "\\Delta"
  | 'Θ' => "\\Theta"
  | 'Λ' => "\\Lambda"
  | 'Σ' => "\\Sigma"
  | 'Φ' => "\\Phi"
  | 'Ξ' => "\\Xi"
  | 'Π' => "\\Pi"
  | 'Ψ' => "\\Psi"
  | 'Ω' => "\\Omega"

  | 'ℵ' => "\\aleph"

  | '₁' => "_1"
  | '₂' => "_2"
  | '₃' => "_3"
  | '₄' => "_4"
  | '₅' => "_5"
  | '₆' => "_6"
  | '₇' => "_7"
  | '₈' => "_8"
  | '₉' => "_9"
  | '₀' => "_0"
  | 'ₐ' => "_a"
  | 'ᵢ' => "_i"
  | 'ⱼ' => "_j"
  | 'ₙ' => "_n"
  | 'ₘ' => "_m"

  | '_' => "\\_"
  | '{' => "\\{"
  | '}' => "\\}"
  --| '\'' => "\\prime}"
  | c => c.toString